server {
        listen  80;
        server_name  ball.luckykingegy.com;
        root /www/static/release/ball/egyBall/advertising1;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}

server {
        listen  80;
        server_name  egyball1.luckykingegy.com;
        root /www/static/release/ball/egyBall/promotion1;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}
server {
        listen  80;
        server_name  egyball2.luckykingegy.com;
        root /www/static/release/ball/egyBall/promotion2;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}
server {
        listen  80;
        server_name  egyball3.luckykingegy.com;
        root /www/static/release/ball/egyBall/promotion3;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}

server {
        listen  80;
        server_name  egyball.luckykingegy.com;
        root /www/static/release/ball/egyBall/share1;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}