server {
        listen  80;
        server_name  dash.luckyinc.net;
        root /www/static/release/lgm-dev/web;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}
