server {
        listen  80;
        server_name  jp77.xyz www.jp77.xyz;
        root /www/static/release/jp/jp77.xyz;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}

server {
        listen  80;
        server_name  jp168.online www.jp168.online;
        root /www/static/release/jp/jp168.online;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}

server {
        listen  80;
        server_name  jp168.xyz www.jp168.xyz;
        root /www/static/release/jp/jp168.xyz;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}
