server {
        listen  80;
        server_name  anubisriches-adv.pages.dev;
        root /www/static/release/anubisriches/anubisriches/share1;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}

server {
        listen  80;
        server_name  mahjongidr-share.pages.dev;
        root /www/static/release/anubisriches/mahjongidr/share1;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}

server {
        listen  80;
        server_name  win8.vip88b.net;
        root /www/static/release/anubisriches/win8game/share1;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}