server {
        listen  80;
        server_name  game.enjoygg.com;
        root /www/static/release/enjoy/enjoyplusplus/advertising5;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}

server {
        listen  80;
        server_name  play.enjoygg.com;
        root /www/static/release/enjoy/enjoyplusplus/advertising6;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}

server {
        listen  80;
        server_name  fun.enjoygg.com;
        root /www/static/release/enjoy/enjoyplusplus/advertising7;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}

server {
        listen  80;
        server_name  www.enjoyplusplus.com;
        root /www/static/release/enjoy/enjoyplusplus/share1;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}