server {
        listen  80;
        server_name  d2lots7swzved6.cloudfront.net diacdxkrq2bu7.cloudfront.net;
        root /www/static/release/app.domain/web;

        location / {
            expires 5m;
        }
}
