server {
        listen  80;
        server_name  fun.goldnile.xyz;
        root /www/static/release/goldnile/goldnile/advertising1;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}
server {
        listen  80;
        server_name  goldnile.dg91.uk;
        root /www/static/release/goldnile/goldnile/advertising2;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}
server {
        listen  80;
        server_name  nile.dg91.uk;
        root /www/static/release/goldnile/goldnile/advertising3;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}

server {
        listen  80;
        server_name  app.goldnile.xyz;
        root /www/static/release/goldnile/goldnile/share1;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}