server {
        listen  80;
        server_name  fun.goldnile.xyz;
        root /www/static/release/goldnile/advertising/advertising1;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}

server {
        listen  80;
        server_name  goldnile.dg91.uk;
        root /www/static/release/goldnile/advertising/advertising2;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}
