server {
        listen  80;
        server_name  testdash.afbgaming.app testdash.icgoffice.xyz testdash.ligaoffice.xyz;
        root /www/static/release/appmgr-test/web;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}
