server {
        listen  80;

        server_name  testdash.afbgaming.app testdash.icgoffice.xyz testdash.ligaoffice.xyz;

        location / {
		root /www/static/release/appmgr-test/web;
        }
}
