server {
        listen  80;
        server_name  devdash.afbgaming.app;
        root /www/static/release/appmgr/dev;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}

server {
        listen  80;
        server_name  testdash.afbgaming.app testdash.icgoffice.xyz testdash.ligaoffice.xyz;
        root /www/static/release/appmgr/test;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}

server {
        listen  80;
        server_name  dash.afbgaming.app dash.icgoffice.xyz dash.ligaoffice.xyz;
        root /www/static/release/appmgr/prod;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}
