server {
        listen  80;
        server_name  dash.luckyinc.net;
        root /www/static/release/lgm/dev;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}

server {
        listen  80;
        server_name  testdash.afbok.com;
        root /www/static/release/lgm/test;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}

server {
        listen  80;
        server_name  dash.afbok.com m.afbok.com nm.afbok.com;
        root /www/static/release/lgm/prod;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}
