server {
        listen  80;
        server_name  devdash.afbgaming.app;
        root /www/static/release/appmgr-dev/web;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }
}
