server {
        listen  80;
        server_name  mysticgame.net www.mysticgame.net;
        root /www/static/release/mysticgame/web;

        location = /index.html {
            expires 5m;
        }

        location / {
            expires 7d;
        }

        
}
